### ISSUE TITLE
document iam policy requirements

### ISSUE THREAD

**Issue by Thomas-Hirsch** [moj-analytical-services/pydbtools#2]
pydbtools (and indeed dbtools) outputs to the bucket `alpha-athena-query-dump`. While I think it will mostly be used interactively, for those who want to use it in an airflow task, it's worth adding a note in the readme that it'll need to be added to the iam policy in order to work

**Comment by isichei** [comment]
This should now be solved by [iam_builder](https://github.com/moj-analytical-services/iam_builder).

However leaving open as not added to AP guidance
