### ISSUE TITLE
CCDE-294: need to provide database name to updated `read_sql_query` method

### ISSUE THREAD

**Issue by isichei** [moj-analytical-services/pydbtools#51]
In the latest awswrangler package you need to provide a database in your queries instead of `None` (what we used to do).

To get a work around for this you will need to use the existing SQL parser functionality in the package to get a database name and then pass that database name into `awswrangler` if the user provides `database=None` (if they specify the database value then the package doesn't need to do anything)

**Comment by mratford** [comment]
https://github.com/moj-analytical-services/pydbtools/tree/give_db_name
