### ISSUE TITLE
CCDE-332: Create ability to drop glue table and contents in one function

### ISSUE THREAD

**Issue by isichei** [moj-analytical-services/pydbtools#54]
`pydbtools` should have a function to drop table and its s3 contents you can do this in `aws-wrangler`.

I wrote a basic version just in a random script for my current project but it would be good to be properly in `pydbtools`.

```python
def big_drop(table, db_name):
    path = wr.catalog.get_table_location(database=db_name, table=table)
    wr.s3.delete_objects(path)
    wr.catalog.delete_table_if_exists(database=db_name, table=table)
```

Would also be good to…

- Add a function to drop a partition rather than a table I think aws-wrangler does the same thing as above but just for a specific partition within a table.

- Add a function to drop a whole database basically gets all the table names from a database, iterates through all the table names and calls the delete table function as mentioned above. Then finally deletes the glue database.

**Comment by mratford** [comment]
https://github.com/moj-analytical-services/pydbtools/pull/58
